### PR TITLE
test case for #303

### PR DESCRIPTION
**Pull request by gracile-fr**

### CODE REVIEW

**Comment by gracile-fr** [comment]
sorry for all this mess. This is failing, but it was already the case with your last commit: https://circleci.com/gh/ZotPlus/zotero-better-bibtex/1040

**Comment by retorquere** [comment]
I don't see any mess? Test has been integrated - thanks.

**Comment by gracile-fr** [comment]
[I was referring to the long series of commits and squashes (visible in #303).]
Are you going to release that shortly?

**Comment by retorquere** [comment]
I thought I did? I'll check when I get home.

**Comment by retorquere** [comment]
I did, 1.2.19 has it.

**Comment by retorquere** [comment]
Nope, sorry, read that wrong. 1.2.20 will have it.

**Pull request merged**
