### PR TITLE
Fix typo stature->statute (zotero item type)

### PR DESCRIPTION
**Pull request by gracile-fr**
Zotero's Bill and Statute types are @legislation in BibLaTeX.

### CODE REVIEW

**Comment by retorquere** [comment]
Whoops, thanks!

**Comment by retorquere** [comment]
Do you perchance have a test reference for this? Easy to generate by right-clicking the reference and selecting "report zotplus error" (or adding it as a pull request in the "test/fixtures/export" directory). I prefer to have tests for fixes -- best way to prevent regression.

**Comment by gracile-fr** [comment]
Not a complete reference, but it seems sufficient for a basic test: DX2IWBD4

**Comment by retorquere** [comment]
Something isn't right yet -- I get a "misc", not a "legislation" export. I'll look into in the morning.

**Comment by retorquere** [comment]
Well duh -- I hadn't pulled the merge into my local repo. Tests run green.

**Comment by gracile-fr** [comment]
I still get a "misc", not a "legislation" export.

**Comment by retorquere** [comment]
Probably related to #285 -- builds are running for 1.2.7 which will drop the cache.

**Comment by retorquere** [comment]
1.2.7 is out.

**Comment by gracile-fr** [comment]
Fixed, thanks.

**Pull request merged**
