### PR TITLE
Fix book -> mvbook (multi-volume book) export

### PR DESCRIPTION
**Pull request by gracile-fr**
Cf. https://github.com/zotero/translators/pull/928

At the moment, the BibLaTeX translator converts a book which has its volume field filled into a multi-volume entry type <code>@mvbook</code> This is a confusion between (number of) volumes and volume.

A <code>@mvbook </code>should be created only if the # of Volumes (numberOfVolumes) field is filled. A <code>@mvbook</code> is not one of the individual volumes of a multi-volume book but the multi-volume book itself. 

I've added a test, but I don't know if it has the correct and desired format…

### CODE REVIEW

**Comment by gracile-fr** [comment]
This fails because of old tests which would need to be updated with this PR.

**Comment by retorquere** [comment]
I've looked over those cases -- you can correct the target file of the test, "export/Big whopping library.bib" for those. The log might look massive (https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/73822127), but there's only 7 of them.

**Comment by retorquere** [comment]
Oh BTW *super* thanks for adding a test! The test is nearly correctly formatted -- nothing you could have known, but the bibtex fields are sorted for the tests, so they'll fail right now. You activate the test bu adding them to https://github.com/gracile-fr/zotero-better-bibtex/blob/master/resource/tests/export.feature -- an extra line at https://github.com/gracile-fr/zotero-better-bibtex/blob/master/resource/tests/export.feature#L111 is easiest.

**Comment by gracile-fr** [comment]
Not sure to follow. How can I "correct the target file of the test, "export/Big whopping library.bib" for those"?
I'll add the test here https://github.com/gracile-fr/zotero-better-bibtex/blob/master/resource/tests/export.feature#L111 , but what's the difference with https://github.com/gracile-fr/zotero-better-bibtex/blob/master/resource/tests/export.feature#L131 ?

**Comment by gracile-fr** [comment]
Ok, got it. But should I add the new test to "export/Big whopping library.bib" ?

**Comment by retorquere** [comment]
No. no need to add it there, just the corrections you already made; the bulk test failed for the wrong reason, as it validated an error.

**Comment by gracile-fr** [comment]
I think I need your help: I don't understand why it's still failing.

**Comment by retorquere** [comment]
Ah damn I still need to change that. Just change the "1" into a "2" in the test -- it counts attachments as references. I'll fix that after I merge this.

**Comment by gracile-fr** [comment]
I tried that before, but it's still failing…

**Comment by retorquere** [comment]
Ah, right -- the test runner sorts the bibtex fields to ensure repeatability. You can either manually sort the fields in the bib file, or set the "better-bibtex.tests" property to a non-empty string in about:config while exporting the bib file. I manually sort myself.

**Comment by retorquere** [comment]
I'm sorry about all this -- I assure you it wasn't put in as a gag :) Working in a separate branch on the # references issue.

**Comment by retorquere** [comment]
If this is getting on your nerves, you can leave fixing the tests to me. I can't currently merge however -- it says "this branch has conflicts"

**Comment by gracile-fr** [comment]
no problem. It has conflicts because I forgot to merge upstream changes before creating a new branch. Does a clean PR (ie without merge conflicts) would change anything?
Let me know when you find a solution.

**Comment by retorquere** [comment]
You can just pull in the upstream changes

**Comment by retorquere** [comment]
a clean PR would do the same, but it'd be more work for you.

**Comment by gracile-fr** [comment]
Done. And I could also remove the attachment to be sure that's the problem.

**Comment by retorquere** [comment]
No need -- if the tests pass, it's good.

**Comment by gracile-fr** [comment]
But it fails for the very same reason.

**Comment by retorquere** [comment]
That's just the sorting again. I've merged, I'll handle the sorting. Thanks for all your efforts -- really do appreciate it.

**Comment by gracile-fr** [comment]
maybe because of the "annotation" field, which is not in the .bib ?

**Comment by retorquere** [comment]
Right, looks like it, plus the jabref fields. The baseline against which the library is tested is always a full library export -- I generate those from a separate firefox profile I keep clean just for this.

**Comment by gracile-fr** [comment]
ok, that means you're the only one who could add the test ;-)

**Comment by retorquere** [comment]
Well not really, anyone could, it's just a little involved -- you have to open firefox using the -p flag top open a new profile. Although honestly I often just construct them by hand from a single-entry export. I look at the complaints from the test run, see if they look reasonable, then copy those in.

**Comment by retorquere** [comment]
The test is still failing, but it must be a test runner failure. I'm looking into it.

**Comment by gracile-fr** [comment]
https://github.com/ZotPlus/zotero-better-bibtex/commit/60bc663da8ee25b43f6c0018f669595031fcd3c1#commitcomment-12492679

**Comment by retorquere** [comment]
Thanks, added that. There's another problem though -- the test runner counts the attached note as a separate reference.

**Comment by retorquere** [comment]
A fix for that is now running, I expect a few others to fail now -- no worries

**Comment by retorquere** [comment]
OK, all is green again. Adding tests should now be more intuitive at least for the counts.

**Comment by retorquere** [comment]
a release build has been started.

**Comment by retorquere** [comment]
BTW if you can run the tests locally, there's another quick way to get a reference sample: add a test line with
```
export the library to '/tmp/whatever.bib':
| translator | Better BibLaTeX |
```
but you'll need to review whether the output is actually what you desire (it should obviously be different before and after the fix to be tested has been applied)

**Comment by gracile-fr** [comment]
Great ! Thanks
"if you can run the tests locally" : I'm not sure what does "can" mean exactly here.

**Comment by retorquere** [comment]
I mean simply "if 'rake test' works". The test runner makes several Unix is
assumptions about the environment, I've never tested beyond ubuntu and osx.

**Pull request merged**
