### PR TITLE
Add test for #296

### PR DESCRIPTION
**Pull request by gracile-fr**

### CODE REVIEW

**Comment by retorquere** [comment]
Awesome, thanks!

**Comment by gracile-fr** [comment]
Out of curiosity, why did the test fail?

**Comment by gracile-fr** [comment]
I see:
punctuation that I forgot to move after sorting, e69f1c0b87a5f4b50711d85df1fffa694a37e53c
\+ timestamp 46340f26b2fee0de6fa6cce0236c41126ab2564e
\+ filename also 780c9f3e0df1d00a06e2766940e11de75ab06f92 ?

**Comment by retorquere** [comment]
It failed because of the sorting and the timestamp, yes; the filename issue simply made it not match any tests, which counts as a failure on my Travis setup. I've added a little text to https://zotplus.github.io/support.html to outline this. Far from complete, most likely.

**Comment by gracile-fr** [comment]
ok!<blockquote>You get this if you export your whole library, and your whole library just happens to consist only of your test references.</blockquote>With JabRef, right? It could be precised (fwiw I only use Zotero).

**Comment by retorquere** [comment]
Nope, with Zotero. I don't use JabRef at all.

**Comment by gracile-fr** [comment]
ah, ok. That's because I'm directly exporting from My Library…

**Comment by retorquere** [comment]
It's a chore, which is why I usually add it by hand.

**Pull request merged**
