### PR TITLE
Prettier bulk clear confirm dialog (title, centered)

### PR DESCRIPTION
**Pull request by gracile-fr**
This should work but I'm not able to test this small change because running from git is impossible for me (<i>TypeError: Zotero.BetterBibTeX is undefined</i> - <a href="https://github.com/ZotPlus/zotero-report-customizer/pull/10#issuecomment-121653677">same error with ZRC</a>)

Also there's only two changes to merge: bulk-clear-confirm.xul keymanager.coffee

I have a problem with all the others files: when cloning this repo, I got a bunch of errors because of forbidden characters in filename on Windows… and they were deleted locally. I'm not able to revert this.

<i>error: Invalid path 'test/fixtures/export/Empty bibtex: clause in extra gobbles whatever follows #99.bib'
error: Invalid path 'test/fixtures/export/Empty bibtex: clause in extra gobbles whatever follows #99.json'
error: Invalid path 'test/fixtures/export/Export "Forthcoming" as "Forthcoming".bib'
error: Invalid path 'test/fixtures/export/Export "Forthcoming" as "Forthcoming".json'
error: Invalid path 'test/fixtures/export/Export error for items without publicationTitle and "Preserve BibTeX variables" enabled #201.bib'
error: Invalid path 'test/fixtures/export/Export error for items without publicationTitle and "Preserve BibTeX variables" enabled #201.json'
error: Invalid path 'test/fixtures/export/German Umlaut "separated" by brackets#146.bib'
error: Invalid path 'test/fixtures/export/German Umlaut "separated" by brackets#146.json'
error: unable to create file test/fixtures/import/Better BibTeX.013/files/32/,.;'[]\{\}\`-=~!@#$%^&()_+.pdf (No such file or directory)
error: unable to create file test/fixtures/import/Better BibTeX.013/some/path/,.;'[]\{\}\`-=~!@#$%^&()_+.pdf (No such file or directory)
fatal: unable to checkout working tree</i>

### CODE REVIEW

**Comment by retorquere** [comment]
Well that is silly; according to https://msdn.microsoft.com/en-us/library/aa365247, the # character is allowed. In any case, I've renamed all the files with hashes in them, could you re-do your pull request from that?

**Comment by gracile-fr** [comment]
I'll make a fresh fork, clone and try again, yes.

**Comment by gracile-fr** [comment]
exactly the same issue when, in git bash, I clone the repo:

<i>$ git clone https://github.com/gracile-fr/zotero-better-bibtex
Cloning into 'zotero-better-bibtex'...
remote: Counting objects: 14563, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 14563 (delta 15), reused 0 (delta 0), pack-reused 14511
Receiving objects: 100% (14563/14563), 79.82 MiB | 309.00 KiB/s, done.
Resolving deltas: 100% (8802/8802), done.
Checking connectivity... done.
error: Invalid path 'test/fixtures/export/Empty bibtex: clause in extra gobbles
whatever follows [99].bib'
error: Invalid path 'test/fixtures/export/Empty bibtex: clause in extra gobbles
whatever follows [99].json'
error: Invalid path 'test/fixtures/export/Export "Forthcoming" as "Forthcoming".
bib'
error: Invalid path 'test/fixtures/export/Export "Forthcoming" as "Forthcoming".
json'
error: Invalid path 'test/fixtures/export/Export error for items without publica
tionTitle and "Preserve BibTeX variables" enabled [201].bib'
error: Invalid path 'test/fixtures/export/Export error for items without publica
tionTitle and "Preserve BibTeX variables" enabled [201].json'
error: Invalid path 'test/fixtures/export/German Umlaut "separated" by brackets
[146].bib'
error: Invalid path 'test/fixtures/export/German Umlaut "separated" by brackets
[146].json'
error: unable to create file test/fixtures/import/Better BibTeX.013/files/32/,.;
'[]\{\}`-=~!@$%^&()_+.pdf (No such file or directory)
error: unable to create file test/fixtures/import/Better BibTeX.013/some/path/,.
;'[]\{\}`-=~!@$%^&()_+.pdf (No such file or directory)
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'</i>

**Comment by gracile-fr** [comment]
That's because there's still some forbidden chars <code>\/:*?"<>|</code>.
Some colons <code>:</code> quotes <code>"</code> slashes <code>/</code> and anti-slashes <code>\</code>.

I'm not entirely clear on the two last errors (error: unable to create file…). The maximum length for a path is 260 characters but that's not the case here.

**Comment by gracile-fr** [comment]
And the hash <code>#</code> character was not at fault, it's not necessary to replace it.

**Comment by retorquere** [comment]
Ah bugger, I'll do a scan for those when I'm back home.

**Comment by retorquere** [comment]
I don't mean to put you through any hoops btw, but if I simply manually
pick these things out you wouldn't get credit in the got logs, plus I want
to have the unintentional windows hostility fixed anyway.

**Comment by gracile-fr** [comment]
Credit is not a problem, but I've already another small pr (a bug fix) and that would become tedious for you to manually pick all of them (if any).

**Comment by retorquere** [comment]
OK, is the current state OK for windows?

**Comment by retorquere** [comment]
On f83b090506964b4658be00a2e1f3a32d10f31289 all tests run green after the remame, so best use that or later.

**Comment by gracile-fr** [comment]
Thanks, no more problem to clone the repo: #283 
(I'm still not able to run bbt from my git checkout but that's a different issue)

**Comment by retorquere** [comment]
I don't run BBT from a git repo myself.

**Comment by gracile-fr** [comment]
<blockquote>I don't run BBT from a git repo myself.</blockquote>How do you run it? That could help to fix my problem.

**Comment by retorquere** [comment]
I just build & install it; installing is just a double-click on the xpi, and it makes sure it fully restarts Firefox/Zotero. You need to have rake working in any case, even if you were to run out of git.

**Pull request closed without merging**
